services:
  # Web service
  - type: web
    name: purrfect-trivia
    env: node
    buildCommand: npm install && npm run build 
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: purrfect-trivia-db
          property: connectionString
    autoDeploy: true

databases:
  - name: purrfect-trivia-db
    plan: starter