services:
  - type: web
    name: purrfect-trivia
    env: node
    buildCommand: npm install && ./build-render.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production